export const projects = [
  {
    title: "AI Wiki Toolbox",
    description: "Comprehensive resource hub for AI tools and their creative applications.",
    longDescription: "AI Wiki Toolbox helps users discover, review, and learn about AI tools in various industries.",
    category: "Documentation",
    slug: "ai-wiki-toolbox",
    year: "2024",
    tags: ["Documentation", "AI", "Resources"],
    heroImage: "/placeholder.svg?height=400&width=800",
    images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    features: [
      "AI tools directory",
      "User reviews and ratings",
      "Prompt engineering tips",
      "Community submissions"
    ],
    technologies: ["Next.js", "Tailwind CSS", "AWS DynamoDB"],
    challenges: "Structuring content for discoverability.",
    solution: "Built intuitive categories and fast filtering.",
    results: "Growing community and tool submissions.",
    liveUrl: "https://www.aiwikitoolbox.com/",
    githubUrl: "",
  },
  {
    title: "Memoir Wizard",
    description: "AI-powered memoir writing assistant that helps users craft their life stories.",
    longDescription: "Guided AI tool that helps users write their life story with writing prompts, structure suggestions, and export options.",
    category: "AI Tools",
    slug: "memoir-wizard",
    year: "2024",
    tags: ["AI", "Writing", "Storytelling"],
    heroImage: "/placeholder.svg?height=400&width=800",
    images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    features: [
      "AI-generated writing prompts",
      "Chapter templates",
      "Photo and memory uploads",
      "Export to PDF / ebook"
    ],
    technologies: ["Next.js", "OpenAI", "Tailwind CSS"],
    challenges: "Simplifying memoir writing.",
    solution: "Guided AI writing experience.",
    results: "High user engagement.",
    liveUrl: "https://memoir-wizard.vercel.app/",
    githubUrl: "",
  },
  {
    title: "Sharespace NZ",
    description: "Community platform for house sharing, flatmates, and tiny home land listings.",
    longDescription: "A community-driven NZ site for house shares and land sharing with user profiles, messaging, and reviews.",
    category: "Community",
    slug: "sharespace-nz",
    year: "2024",
    tags: ["Community", "Housing", "NZ"],
    heroImage: "/placeholder.svg?height=400&width=800",
    images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    features: [
      "Listings for shares and land",
      "Secure messaging",
      "User reviews",
      "Verified profiles"
    ],
    technologies: ["Next.js", "AWS DynamoDB", "AWS Cognito", "Tailwind CSS"],
    challenges: "Building trust in an online community.",
    solution: "Verified profiles and clear listings.",
    results: "Active early users.",
    liveUrl: "https://houseshare-app.vercel.app/",
    githubUrl: "",
  },
  {
    title: "Lafaek Children's Book Library",
    description: "Interactive digital library platform for Timor-Leste children.",
    longDescription: "A bilingual library offering children's books in Tetum and Portuguese, with interactive reading features.",
    category: "Education",
    slug: "lafaek-childrens-book-library",
    year: "2024",
    tags: ["Education", "Children", "Library"],
    heroImage: "/placeholder.svg?height=400&width=800",
    images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    features: [
      "Bilingual book collection",
      "Interactive reader",
      "Audio narration",
      "Offline reading"
    ],
    technologies: ["Next.js", "Tailwind CSS", "Supabase"],
    challenges: "Supporting multiple languages.",
    solution: "Flexible book formats and UI.",
    results: "Popular among young learners.",
    liveUrl: "https://lafaek-childrens-book-library.vercel.app/",
    githubUrl: "",
  },
  {
    title: "Timor Tourism & Booking Site",
    description: "Tourism and booking platform for Timor-Leste tours and operators.",
    longDescription: "An online booking platform for Timor-Leste operators, tours, and accommodations with multilingual support.",
    category: "Travel",
    slug: "timor-booking-site",
    year: "2024",
    tags: ["Travel", "Booking", "Timor-Leste"],
    heroImage: "/placeholder.svg?height=400&width=800",
    images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    features: [
      "Tour listings",
      "Online bookings",
      "Multilingual support",
      "Operator profiles"
    ],
    technologies: ["Next.js", "Tailwind CSS"],
    challenges: "Building trust for online payments.",
    solution: "Simple and secure booking process.",
    results: "Positive feedback from local operators.",
    liveUrl: "https://timor-booking.vercel.app/",
    githubUrl: "",
  },
  {
    title: "ANATUR Tourism Homepage",
    description: "Homepage for ANATUR, the national tourism authority of Timor-Leste.",
    longDescription: "Landing page for ANATUR to promote Timor-Leste's unique tourism offerings.",
    category: "Travel",
    slug: "anatur-tourism-homepage",
    year: "2024",
    tags: ["Tourism", "Government", "Timor-Leste"],
    heroImage: "/placeholder.svg?height=400&width=800",
    images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    features: [
      "Tourism landing page",
      "Highlights and imagery",
      "Government branding",
      "Cultural promotions"
    ],
    technologies: ["Next.js", "Tailwind CSS"],
    challenges: "Capturing national tourism identity.",
    solution: "Image-led design.",
    results: "First national tourism site.",
    liveUrl: "https://anatur-homepage.vercel.app/",
    githubUrl: "",
  },
  {
    title: "L&D Portfolio Hub",
    description: "Showcase of learning design portfolio and capabilities.",
    longDescription: "A portfolio site displaying learning design projects, workshops, and AI-based learning solutions.",
    category: "Portfolio",
    slug: "ld-portfolio-hub",
    year: "2024",
    tags: ["Portfolio", "L&D", "Showcase"],
    heroImage: "/placeholder.svg?height=400&width=800",
    images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    features: [
      "Portfolio grid",
      "Case studies",
      "Project highlights",
      "Client testimonials"
    ],
    technologies: ["Next.js", "Tailwind CSS"],
    challenges: "Organising diverse project types.",
    solution: "Grid-based layout with detailed project pages.",
    results: "Professional online presence.",
    liveUrl: "https://ld-portfolio-two.vercel.app/",
    githubUrl: "",
  },
  {
    title: "Oracle Card Generator",
    description: "Digital platform for creating and sharing custom oracle card decks.",
    longDescription: "Enables creators to design oracle card decks with text, images, and AI-generated interpretations.",
    category: "Creative Tools",
    slug: "oracle-card-generator",
    year: "2024",
    tags: ["Creative", "AI Art", "Spirituality"],
    heroImage: "/placeholder.svg?height=400&width=800",
    images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    features: [
      "Custom deck builder",
      "AI-generated card meanings",
      "Download and share decks",
      "Interactive card spreads"
    ],
    technologies: ["Next.js", "Tailwind CSS", "OpenAI"],
    challenges: "Balancing flexibility and ease of use.",
    solution: "Simple deck builder UI.",
    results: "Popular among creatives.",
    liveUrl: "https://v0-oracle-card-app-design.vercel.app/",
    githubUrl: "",
  },
]
